"""Add is_timer_active to User

Revision ID: 42ff9c1254b1
Revises: ee399dead833
Create Date: 2026-04-30 17:04:01.499678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ff9c1254b1'
down_revision: Union[str, Sequence[str], None] = 'ee399dead833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_timer_active', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_timer_active')
    # ### end Alembic commands ###
